# Generated by Django 2.0.4 on 2018-12-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reference',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
